# Commander
bindr = SUPER, SUPER_L, exec, /usr/bin/commander --tap
bindo = SUPER, SUPER_L, exec, /usr/bin/commander --voice-trigger-start
bindr = SUPER, SUPER_L, exec, /usr/bin/commander --voice-trigger-stop
